# Documentation: https://github.com/atusy/kakehashi/blob/main/docs/README.md

autoInstall = true

[languages.markdown]
aliases = ["rmd", "qmd"]

[languageServers.lua_ls]
cmd = ["lua-language-server"]
languages = ["lua"]

[languageServers.pyright]
cmd = ["pyright-langserver", "--stdio"]
languages = ["python"]

[captureMappings._.highlights]
"markup.heading" = "class"
"markup.heading.1" = "class"
"markup.heading.2" = "class"
"markup.heading.3" = "class"
"markup.heading.4" = "class"
"markup.heading.5" = "class"
"markup.heading.6" = "class"
"markup.italic" = "keyword"
"markup.link.label" = "keyword"
"markup.link.url" = ""
"markup.link" = ""
"markup.list.checked" = "property"
"markup.list.unchecked" = "property"
"markup.list" = "property"
"markup.math" = ""
"markup.quote" = "string"
"markup.raw.block" = "string"
"markup.raw" = "string"
"markup.strikethrough" = "keyword.deprecated"
"markup.strong" = "keyword"
"markup.underline" = "keyword"
