# Documentation: https://github.com/atusy/kakehashi/blob/main/docs/README.md

autoInstall = true

[languages.markdown]
aliases = ["rmd", "qmd"]

# For Neovim, languageServers are setup by using Neovim Lua API
# The below is just an example of how to setup a language server
[languageServers.basedpyright]
cmd = ["basedpyright-langserver", "--stdio"]
languages = ["python"]

[captureMappings._.highlights]
"markup.heading" = "class"
"markup.heading.1" = "class"
"markup.heading.2" = "class"
"markup.heading.3" = "class"
"markup.heading.4" = "class"
"markup.heading.5" = "class"
"markup.heading.6" = "class"
"markup.italic" = "keyword"
"markup.link.label" = "keyword"
"markup.link.url" = ""
"markup.link" = ""
"markup.list.checked" = "property"
"markup.list.unchecked" = "property"
"markup.list" = "property"
"markup.math" = ""
"markup.quote" = "string"
"markup.raw.block" = "string"
"markup.raw" = "string"
"markup.strikethrough" = "keyword.deprecated"
"markup.strong" = "keyword"
"markup.underline" = "keyword"
